(cl:defpackage dji_sdk-msg
  (:use )
  (:export
   "<WAYPOINT>"
   "WAYPOINT"
   "<GIMBAL>"
   "GIMBAL"
   "<MISSIONWAYPOINT>"
   "MISSIONWAYPOINT"
   "<WAYPOINTLIST>"
   "WAYPOINTLIST"
   "<MOBILEDATA>"
   "MOBILEDATA"
   "<MISSIONWAYPOINTACTION>"
   "MISSIONWAYPOINTACTION"
   "<MISSIONHOTPOINTTASK>"
   "MISSIONHOTPOINTTASK"
   "<MISSIONWAYPOINTTASK>"
   "MISSIONWAYPOINTTASK"
  ))

